fn main() {
    // un-mutable
    let x = 5;
    println!("The value of x is {}", x);

    // mutable
    let mut y = 10;
    println!("The value of y is {}", y);
    y = 11;
    println!("The value of y is now {}", y);
}# Generated by Cargo
# will have compiled files and executables
debug/
target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these, which store debugging information
*.pdb